services:
  db_postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxihail
      PGDATA: /data/postgres
    volumes:
#      - db_postgres:/data/postgres
       - $HOME/docker/volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped

#networks:
#  db:
#    driver: bridge