services:
  db_taxihail_core:
    container_name: db_taxihail_core
    image: postgres
    environment:
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxihail_core
    volumes:
       - $HOME/docker/volumes/taxihail/core:/var/lib/postgresql/data
    ports:
      - "5332:5432"
    restart: unless-stopped

  db_taxihail_location:
    container_name: db_taxihail_location
    image: postgres
    environment:
      POSTGRES_USER: taxi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: taxihail_location
    volumes:
      - $HOME/docker/volumes/taxihail/location:/var/lib/postgresql/data
    ports:
      - "5333:5432"
    restart: unless-stopped

  zookeeper:
    image: docker.io/bitnami/zookeeper:3.8
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ENABLE_KRAFT=no
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
    depends_on:
      - zookeeper

networks:
  app-tier:
    driver: bridge

volumes:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local