application:
  security:
    jwt:
      secret-key: 5166546A576E5A7234753778214125442A472D4B6150645267556B5870327336
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5332/taxihail_core
    username: taxi
    password: password
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      mode: never
      data-locations: [classpath:seed_data.sql]

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect


logging:
  level:
    org.hibernate.SQL: DEBUG